#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum Key {
    Back,
    Tab,
    Clear,
    Return,
    Shift,
    Ctrl,
    Menu,
    Pause,
    CapsLock,
    Esc,
    Space,
    PageUp,
    PageDown,
    End,
    Home,
    Left,
    Up,
    Right,
    Down,
    Select,
    Print,
    Execute,
    PrintScreen,
    Insert,
    Delete,
    Help,
    N0,
    N1,
    N2,
    N3,
    N4,
    N5,
    N6,
    N7,
    N8,
    N9,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Win,
    WinR,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    Multiply,
    Add,
    Spectator,
    Subtract,
    Decimal,
    Devide,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    NumLock,
    ScrollLock,
    ShiftLeft,
    ShiftRight,
    CtrlLeft,
    CtrlRight,
    AltLeft,
    AltRight,
    Plus,
    Comma,
    Minus,
    Period,
}

impl Key {
    pub fn try_from_vk(code: u8) -> Result<Self, ()> {
        match code {
            0x08 => Ok(Self::Back),
            0x09 => Ok(Self::Tab),
            0x0C => Ok(Self::Clear),
            0x0D => Ok(Self::Return),
            0x10 => Ok(Self::Shift),
            0x11 => Ok(Self::Ctrl),
            0x12 => Ok(Self::Menu),
            0x13 => Ok(Self::Pause),
            0x14 => Ok(Self::CapsLock),
            0x1B => Ok(Self::Esc),
            0x20 => Ok(Self::Space),
            0x21 => Ok(Self::PageUp),
            0x22 => Ok(Self::PageDown),
            0x23 => Ok(Self::End),
            0x24 => Ok(Self::Home),
            0x25 => Ok(Self::Left),
            0x26 => Ok(Self::Up),
            0x27 => Ok(Self::Right),
            0x28 => Ok(Self::Down),
            0x29 => Ok(Self::Select),
            0x2A => Ok(Self::Print),
            0x2B => Ok(Self::Execute),
            0x2C => Ok(Self::PrintScreen),
            0x2D => Ok(Self::Insert),
            0x2E => Ok(Self::Delete),
            0x2F => Ok(Self::Help),
            0x30 => Ok(Self::N0),
            0x31 => Ok(Self::N1),
            0x32 => Ok(Self::N2),
            0x33 => Ok(Self::N3),
            0x34 => Ok(Self::N4),
            0x35 => Ok(Self::N5),
            0x36 => Ok(Self::N6),
            0x37 => Ok(Self::N7),
            0x38 => Ok(Self::N8),
            0x39 => Ok(Self::N9),
            0x41 => Ok(Self::A),
            0x42 => Ok(Self::B),
            0x43 => Ok(Self::C),
            0x44 => Ok(Self::D),
            0x45 => Ok(Self::E),
            0x46 => Ok(Self::F),
            0x47 => Ok(Self::G),
            0x48 => Ok(Self::H),
            0x49 => Ok(Self::I),
            0x4A => Ok(Self::J),
            0x4B => Ok(Self::K),
            0x4C => Ok(Self::L),
            0x4D => Ok(Self::M),
            0x4E => Ok(Self::N),
            0x4F => Ok(Self::O),
            0x50 => Ok(Self::P),
            0x51 => Ok(Self::Q),
            0x52 => Ok(Self::R),
            0x53 => Ok(Self::S),
            0x54 => Ok(Self::T),
            0x55 => Ok(Self::U),
            0x56 => Ok(Self::V),
            0x57 => Ok(Self::W),
            0x58 => Ok(Self::X),
            0x59 => Ok(Self::Y),
            0x5A => Ok(Self::Z),
            0x5B => Ok(Self::Win),
            0x5C => Ok(Self::WinR),
            0x60 => Ok(Self::Numpad0),
            0x61 => Ok(Self::Numpad1),
            0x62 => Ok(Self::Numpad2),
            0x63 => Ok(Self::Numpad3),
            0x64 => Ok(Self::Numpad4),
            0x65 => Ok(Self::Numpad5),
            0x66 => Ok(Self::Numpad6),
            0x67 => Ok(Self::Numpad7),
            0x68 => Ok(Self::Numpad8),
            0x69 => Ok(Self::Numpad9),
            0x6A => Ok(Self::Multiply),
            0x6B => Ok(Self::Add),
            0x6C => Ok(Self::Spectator),
            0x6D => Ok(Self::Subtract),
            0x6E => Ok(Self::Decimal),
            0x6F => Ok(Self::Devide),
            0x70 => Ok(Self::F1),
            0x71 => Ok(Self::F2),
            0x72 => Ok(Self::F3),
            0x73 => Ok(Self::F4),
            0x74 => Ok(Self::F5),
            0x75 => Ok(Self::F6),
            0x76 => Ok(Self::F7),
            0x77 => Ok(Self::F8),
            0x78 => Ok(Self::F9),
            0x79 => Ok(Self::F10),
            0x7A => Ok(Self::F11),
            0x7B => Ok(Self::F12),
            0x7C => Ok(Self::F13),
            0x7D => Ok(Self::F14),
            0x7E => Ok(Self::F15),
            0x7F => Ok(Self::F16),
            0x80 => Ok(Self::F17),
            0x81 => Ok(Self::F18),
            0x82 => Ok(Self::F19),
            0x83 => Ok(Self::F20),
            0x84 => Ok(Self::F21),
            0x85 => Ok(Self::F22),
            0x86 => Ok(Self::F23),
            0x87 => Ok(Self::F24),
            0x90 => Ok(Self::NumLock),
            0x91 => Ok(Self::ScrollLock),
            0xA0 => Ok(Self::ShiftLeft),
            0xA1 => Ok(Self::ShiftRight),
            0xA2 => Ok(Self::CtrlLeft),
            0xA3 => Ok(Self::CtrlRight),
            0xA4 => Ok(Self::AltLeft),
            0xA5 => Ok(Self::AltRight),
            0xBB => Ok(Self::Plus),
            0xBC => Ok(Self::Comma),
            0xBD => Ok(Self::Minus),
            0xBE => Ok(Self::Period),
            _ => Err(()),
        }
    }
}
