#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum Key {
    Back,
    Tab,
    Clear,
    Return,
    Shift,
    Ctrl,
    Menu,
    Pause,
    CapsLock,
    Esc,
    Space,
    PageUp,
    PageDown,
    End,
    Home,
    Left,
    Up,
    Right,
    Down,
    Select,
    Print,
    Execute,
    PrintScreen,
    Insert,
    Delete,
    Help,
    N0,
    N1,
    N2,
    N3,
    N4,
    N5,
    N6,
    N7,
    N8,
    N9,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Win,
    WinR,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    Multiply,
    Add,
    Spectator,
    Subtract,
    Decimal,
    Devide,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    NumLock,
    ScrollLock,
    ShiftLeft,
    ShiftRight,
    CtrlLeft,
    CtrlRight,
    AltLeft,
    AltRight,
    Plus,
    Comma,
    Minus,
    Period,

    Unknown
}

impl Key {
    pub fn from_vk_code(code: u8) -> Self {
        match code {
            0x08 => Self::Back,
            0x09 => Self::Tab,
            0x0C => Self::Clear,
            0x0D => Self::Return,
            0x10 => Self::Shift,
            0x11 => Self::Ctrl,
            0x12 => Self::Menu,
            0x13 => Self::Pause,
            0x14 => Self::CapsLock,
            0x1B => Self::Esc,
            0x20 => Self::Space,
            0x21 => Self::PageUp,
            0x22 => Self::PageDown,
            0x23 => Self::End,
            0x24 => Self::Home,
            0x25 => Self::Left,
            0x26 => Self::Up,
            0x27 => Self::Right,
            0x28 => Self::Down,
            0x29 => Self::Select,
            0x2A => Self::Print,
            0x2B => Self::Execute,
            0x2C => Self::PrintScreen,
            0x2D => Self::Insert,
            0x2E => Self::Delete,
            0x2F => Self::Help,
            0x30 => Self::N0,
            0x31 => Self::N1,
            0x32 => Self::N2,
            0x33 => Self::N3,
            0x34 => Self::N4,
            0x35 => Self::N5,
            0x36 => Self::N6,
            0x37 => Self::N7,
            0x38 => Self::N8,
            0x39 => Self::N9,
            0x41 => Self::A,
            0x42 => Self::B,
            0x43 => Self::C,
            0x44 => Self::D,
            0x45 => Self::E,
            0x46 => Self::F,
            0x47 => Self::G,
            0x48 => Self::H,
            0x49 => Self::I,
            0x4A => Self::J,
            0x4B => Self::K,
            0x4C => Self::L,
            0x4D => Self::M,
            0x4E => Self::N,
            0x4F => Self::O,
            0x50 => Self::P,
            0x51 => Self::Q,
            0x52 => Self::R,
            0x53 => Self::S,
            0x54 => Self::T,
            0x55 => Self::U,
            0x56 => Self::V,
            0x57 => Self::W,
            0x58 => Self::X,
            0x59 => Self::Y,
            0x5A => Self::Z,
            0x5B => Self::Win,
            0x5C => Self::WinR,
            0x60 => Self::Numpad0,
            0x61 => Self::Numpad1,
            0x62 => Self::Numpad2,
            0x63 => Self::Numpad3,
            0x64 => Self::Numpad4,
            0x65 => Self::Numpad5,
            0x66 => Self::Numpad6,
            0x67 => Self::Numpad7,
            0x68 => Self::Numpad8,
            0x69 => Self::Numpad9,
            0x6A => Self::Multiply,
            0x6B => Self::Add,
            0x6C => Self::Spectator,
            0x6D => Self::Subtract,
            0x6E => Self::Decimal,
            0x6F => Self::Devide,
            0x70 => Self::F1,
            0x71 => Self::F2,
            0x72 => Self::F3,
            0x73 => Self::F4,
            0x74 => Self::F5,
            0x75 => Self::F6,
            0x76 => Self::F7,
            0x77 => Self::F8,
            0x78 => Self::F9,
            0x79 => Self::F10,
            0x7A => Self::F11,
            0x7B => Self::F12,
            0x7C => Self::F13,
            0x7D => Self::F14,
            0x7E => Self::F15,
            0x7F => Self::F16,
            0x80 => Self::F17,
            0x81 => Self::F18,
            0x82 => Self::F19,
            0x83 => Self::F20,
            0x84 => Self::F21,
            0x85 => Self::F22,
            0x86 => Self::F23,
            0x87 => Self::F24,
            0x90 => Self::NumLock,
            0x91 => Self::ScrollLock,
            0xA0 => Self::ShiftLeft,
            0xA1 => Self::ShiftRight,
            0xA2 => Self::CtrlLeft,
            0xA3 => Self::CtrlRight,
            0xA4 => Self::AltLeft,
            0xA5 => Self::AltRight,
            0xBB => Self::Plus,
            0xBC => Self::Comma,
            0xBD => Self::Minus,
            0xBE => Self::Period,
            _ => Self::Unknown,
        }
    }
}
